collections:
  games:
    output: true

defaults:
  - scope:
      path: ''
      type: 'games'
    values:
      layout: 'game'
  - scope:
      path: ''
    values:
      layout: 'default'

pagination:
  enabled: true
  per_page: 10
  permalink: '/page:num/'
  title: ':title | Page :num'
  limit: 0
  sort_field: 'title'
  sort_reverse: false
