collections:
  games:
    output: true

defaults:
  - scope:
      path: ''
      type: 'games'
    values:
      layout: 'game'
  - scope:
      path: ''
    values:
      layout: 'default'

pagination:
  enabled: true
  per_page: 12
  permalink: '/page:num/'
  title: ':title | Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  collections:
    enabled: false
  tags:
    layouts:
      - 'autopage_tag.html'
    title: 'Tag: :tag | Games'
    permalink: '/games/tag/:tag'
